version: '3.8'

services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"  # Port for Jupyter
      - "22:22"      # Port for SSH
    depends_on:
      - postgres
    networks:
      - datacube_network

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datacube
    ports:
      - "5432:5432"  # Port for PostgreSQL
    networks:
      - datacube_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"  # Port for pgAdmin
    networks:
      - datacube_network

networks:
  datacube_network:
